<script setup>
import { computed, reactive, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { LayoutDashboard, FilePenLine, MessageCircle, Image, Tags, Settings, LogOut, Plus, ArrowLeft, Eye, Save, Upload } from '@lucide/vue';
import { api, site, loadSite, listCache, dateLabel, typeLabels } from '../api';
import Editor from '../components/Editor.vue';
import RichBody from '../components/RichBody.vue';
const route = useRoute(), router = useRouter();
const section = computed(() => route.params.section || 'contents');
const sections = [{id:'contents',label:'内容管理',icon:FilePenLine},{id:'comments',label:'评论留言',icon:MessageCircle},{id:'media',label:'图片库',icon:Image},{id:'taxonomies',label:'分类标签',icon:Tags},{id:'settings',label:'站点设置',icon:Settings}];
const login = reactive({username:'',password:''});
const error = ref(''), notice = ref(''), busy = ref(false), items = ref([]), page = ref(1), more = ref(false), selected = ref([]), editing = ref(null), preview = ref(null), statusFilter = ref(''), taxonomy = reactive({kind:'category',name:''}), settings = ref(null);
const empty = () => ({type:'article',status:'draft',title:'',summary:'',body:'',category:'',tags:[],cover:'',url:'',screenshots:[],device:'',instructions:'',video_url:'',show_published_at:true,featured:false,featured_order:0});
async function action(fn) { busy.value = true; error.value='';notice.value='';try { return await fn(); } catch(e) { error.value=e.message; if(e.status===401) { site.isAdmin=false; notice.value='登录已过期，请重新登录；未保存的编辑仍然保留。'; } return null; } finally { busy.value=false; } }
async function signIn() { await action(async()=>{ await api('/auth/login',{method:'POST',body:login}); login.password=''; await loadSite(); }); }
async function signOut() { await action(async()=>{ await api('/auth/logout',{method:'POST'});site.isAdmin=false; editing.value=null; }); }
async function load(append=false) { if(!site.isAdmin) return; await action(async()=>{ if(section.value==='settings') { await loadSite();settings.value=JSON.parse(JSON.stringify(site.settings));return; } const data=await api(`/admin/${section.value}?page=${page.value}&status=${statusFilter.value}`);items.value=append?[...items.value,...data.items]:data.items;more.value=data.hasMore||false;selected.value=[]; }); }
watch([section,()=>site.isAdmin],()=>{page.value=1;items.value=[];if(!editing.value) preview.value=null;load();},{immediate:true});
function create() { editing.value=empty(); notice.value='';error.value=''; }
async function edit(item) { await action(async()=>{ editing.value=await api('/admin/contents/'+item.id); }); }
async function save(status,showPreview=false) { await action(async()=>{ const data=await api('/admin/contents'+(editing.value.id?'/'+editing.value.id:''),{method:editing.value.id?'PUT':'POST',body:{...editing.value,status}});editing.value=data;listCache.clear();notice.value=status==='published'?'已发布，读者现在可以访问。':status==='archived'?'已下架，公开列表、搜索和详情均不可访问。':'草稿已保存。';await loadSite();if(showPreview) preview.value=data; }); }
function leaveEditor() { if(confirm('返回内容列表？请先确认修改已经保存。')) { editing.value=null;page.value=1;load(); } }
async function upload(event,target='media',index=-1) { const file=event.target.files?.[0];if(!file)return;await action(async()=>{const form=new FormData();form.append('file',file);const result=await api('/admin/media',{method:'POST',body:form});if(target==='cover')editing.value.cover=result.url;else if(target==='screenshot')editing.value.screenshots.push(result.url);else if(target==='avatar')settings.value.avatar=result.url;else if(target==='carousel')settings.value.carousel[index].image=result.url;else await load();notice.value='图片已上传并优化。';});event.target.value=''; }
async function deleteComments(ids) { if(!ids.length||!confirm('删除所选评论？原文将清除，其他人的回复仍会保留。'))return;await action(async()=>{await api('/admin/comments/delete',{method:'POST',body:{ids}});await load();notice.value='评论已删除。';}); }
async function reply(item) { const body=prompt('回复 '+item.nickname+'（将以站长身份公开）');if(!body)return;await action(async()=>{await api('/comments',{method:'POST',body:{nickname:site.settings.name,body,replyTo:item.id,contentId:item.content_id}});await load();notice.value='站长回复已发布。';}); }
async function createTaxonomy() { await action(async()=>{await api('/admin/taxonomies',{method:'POST',body:taxonomy});taxonomy.name='';await loadSite();await load();}); }
async function updateTaxonomy(item) { const name=prompt('修改名称，关联内容会同步更新',item.name);if(!name)return;await action(async()=>{await api('/admin/taxonomies/'+item.id,{method:'PUT',body:{name}});listCache.clear();await loadSite();await load();}); }
async function deleteItem(endpoint,id,message) { if(!confirm(message))return;await action(async()=>{await api('/admin/'+endpoint+'/'+id,{method:'DELETE'});await loadSite();await load();}); }
async function saveSettings() { await action(async()=>{await api('/admin/settings',{method:'PUT',body:settings.value});await loadSite();notice.value='站点设置已保存。';}); }
function addSlide() { settings.value.carousel.push({image:'',title:'',action:'preview',url:''}); }
</script>
<template>
  <section v-if="!site.isAdmin" class="login-card"><span class="login-emblem"><LayoutDashboard :size="25"/></span><div class="eyebrow">YOUR CREATIVE SPACE</div><h1>站长登录</h1><p>管理你的作品、知识与日常发现。</p><form @submit.prevent="signIn"><label>用户名<input v-model="login.username" autocomplete="username" required maxlength="80"/></label><label>密码<input v-model="login.password" type="password" autocomplete="current-password" required maxlength="256"/></label><p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="notice" class="notice">{{ notice }}</p><button class="button" :disabled="busy">{{busy?'登录中…':'进入后台'}} <ArrowLeft class="rotate" :size="17"/></button></form><small>仅站长可访问管理功能</small></section>
  <div v-else class="admin-layout"><aside class="admin-sidebar"><h2><LayoutDashboard :size="21"/>创作后台</h2><nav aria-label="后台导航"><RouterLink v-for="s in sections" :key="s.id" :to="'/admin/'+s.id" :class="{active:section===s.id}" @click="editing=null"><component :is="s.icon" :size="18"/>{{s.label}}</RouterLink></nav><button @click="signOut"><LogOut :size="17"/>退出登录</button></aside><div class="admin-content">
    <p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="success" role="status">{{notice}}</p>
    <template v-if="section==='contents'"><template v-if="editing"><button class="back-button" @click="leaveEditor"><ArrowLeft :size="16"/>内容列表</button><div class="admin-heading"><h1>{{editing.id?'编辑内容':'新的创作'}}</h1><span class="pill">{{ {draft:'草稿',published:'已发布',archived:'已下架'}[editing.status] }}</span></div><form class="content-form" @submit.prevent="save('draft')"><div class="form-grid"><label>内容类型<select v-model="editing.type"><option v-for="(name,key) in typeLabels" :value="key" :key="key">{{name}}</option></select></label><label>分类（选填）<select v-model="editing.category"><option value="">不选择分类</option><option v-for="t in site.taxonomies.filter(t=>t.kind==='category')" :key="t.id">{{t.name}}</option></select></label></div><label>标题或名称<input v-model="editing.title" required maxlength="160" placeholder="给这次创作起个名字"/></label><label>{{editing.type==='tool'?'推荐理由（选填）':'摘要或简介（选填）'}}<textarea v-model="editing.summary" rows="3" maxlength="1000"/></label><label>标签（选填）</label><div class="tag-options"><label v-for="t in site.taxonomies.filter(t=>t.kind==='tag')" :key="t.id" class="check-label"><input type="checkbox" :value="t.name" v-model="editing.tags"/>{{t.name}}</label><small v-if="!site.taxonomies.length">需要分类或标签筛选时，可先到“分类标签”添加。</small></div>
      <div class="image-field"><label>{{editing.type==='tool'?'工具图标':'封面或配图'}}<input v-model="editing.cover" placeholder="上传图片后自动填入地址"/></label><label class="button secondary upload-button"><Upload :size="16"/>上传<input type="file" accept="image/png,image/jpeg,image/webp" @change="upload($event,'cover')"/></label><img v-if="editing.cover" :src="editing.cover" alt="封面预览"/></div>
      <label v-if="['game','tool','note'].includes(editing.type)">{{ editing.type==='note' ? '相关链接（选填）' : '外部访问地址（发布时必填）' }}<input v-model="editing.url" type="url" placeholder="https://" maxlength="2048"/></label>
      <template v-if="editing.type!=='tool'"><label>正文 / 详细介绍</label><Editor v-model="editing.body" @error="error=$event"/></template>
      <template v-if="editing.type==='game'"><label>宣传视频 MP4 链接（选填）<input v-model="editing.video_url" type="url" maxlength="2048" placeholder="https://example.com/trailer.mp4"/></label><small class="field-help">填写 HTTPS 的 MP4 文件直链，访客可在游戏详情页直接播放；建议视频约 30 秒。</small><label>设备支持<input v-model="editing.device" maxlength="120" placeholder="例如：手机触控 / 电脑键鼠"/></label><label>操作说明<textarea v-model="editing.instructions" rows="4" maxlength="5000"/></label><label>游戏截图</label><div class="screenshots editing-screenshots"><div v-for="(url,i) in editing.screenshots" :key="i"><img :src="url" alt="截图预览"/><button type="button" @click="editing.screenshots.splice(i,1)">移除</button></div></div><label class="button secondary upload-button">添加截图<input type="file" accept="image/png,image/jpeg,image/webp" @change="upload($event,'screenshot')"/></label></template>
      <div class="featured-controls"><label class="check-label"><input type="checkbox" v-model="editing.featured"/>设为首页精选</label><label>精选顺序（小数值在前）<input v-model.number="editing.featured_order" type="number" min="-10000" max="10000"/></label><label class="check-label"><input type="checkbox" v-model="editing.show_published_at"/>公开显示发布时间</label></div>
      <div class="editor-actions"><button class="button secondary" type="submit" :disabled="busy"><Save :size="16"/>保存草稿</button><button class="button secondary" type="button" :disabled="busy" @click="save(editing.status,true)"><Eye :size="16"/>保存并预览</button><button class="button" type="button" :disabled="busy" @click="save('published')">{{editing.status==='published'?'更新已发布内容':'发布内容'}}</button><button v-if="editing.id && editing.status==='published'" class="button danger" type="button" :disabled="busy" @click="save('archived')">下架</button></div>
    </form></template><template v-else><div class="admin-heading"><div><div class="eyebrow">CONTENT STUDIO</div><h1>把想法写下来</h1></div><button class="button" @click="create"><Plus :size="17"/>新建内容</button></div><div class="admin-filters"><label>发布状态<select v-model="statusFilter" @change="page=1;load()"><option value="">全部状态</option><option value="draft">草稿</option><option value="published">已发布</option><option value="archived">已下架</option></select></label></div><div class="admin-list"><article v-for="item in items" :key="item.id" class="admin-row"><div><span class="pill">{{typeLabels[item.type]}}</span><h3>{{item.title}}</h3><small>{{{draft:'草稿',published:'已发布',archived:'已下架'}[item.status]}} · {{dateLabel(item.updated_at)}}<span v-if="item.featured"> · 精选 #{{item.featured_order}}</span></small></div><button class="button secondary" @click="edit(item)">编辑</button></article></div><div v-if="!items.length" class="empty-small">{{busy?'加载中…':'还没有内容，开始记录第一个想法吧。'}}</div></template></template>
    <template v-else-if="section==='comments'"><div class="admin-heading"><h1>评论与留言</h1><button class="button danger" :disabled="!selected.length || busy" @click="deleteComments(selected)">删除所选 {{selected.length || ''}}</button></div><div class="admin-list"><article v-for="item in items" :key="item.id" class="admin-comment"><label class="check-label"><input type="checkbox" v-model="selected" :value="item.id"/><strong>{{item.nickname}}</strong><span v-if="item.is_admin" class="badge">站长</span><small>{{dateLabel(item.created_at)}}</small></label><small>{{item.content_id?'内容评论':'留言板'}}{{item.root_id?' · 回复':''}}</small><blockquote v-if="item.quote">{{item.quote.nickname}}：{{item.quote.body}}</blockquote><p class="plain-text">{{item.body}}</p><div class="row-actions"><button @click="reply(item)">回复</button><button class="danger-text" @click="deleteComments([item.id])">删除</button></div></article></div><div v-if="!items.length" class="empty-small">{{busy?'加载中…':'还没有评论或留言。'}}</div></template>
    <template v-else-if="section==='media'"><div class="admin-heading"><h1>图片库</h1><label class="button upload-button"><Plus :size="16"/>上传图片<input type="file" accept="image/png,image/jpeg,image/webp" @change="upload($event)"/></label></div><p class="muted">支持 JPEG、PNG、WebP，单张不超过 5 MB。自动优化为 WebP，最长边 1920 像素。</p><div class="media-grid"><article v-for="item in items" :key="item.id"><img :src="item.url" :alt="item.name" loading="lazy"/><strong>{{item.name}}</strong><input :value="item.url" readonly aria-label="图片地址" @focus="$event.target.select()"/><button class="danger-text" @click="deleteItem('media',item.id,'删除这张图片？正在使用的图片会被保护。')">删除图片</button></article></div><div v-if="!items.length" class="empty-small">图片库还是空的。</div></template>
    <template v-else-if="section==='taxonomies'"><div class="admin-heading"><h1>分类与标签</h1></div><form class="taxonomy-form" @submit.prevent="createTaxonomy"><label>类型<select v-model="taxonomy.kind"><option value="category">分类</option><option value="tag">标签</option></select></label><label>名称<input v-model="taxonomy.name" required maxlength="60"/></label><button class="button" :disabled="busy">添加</button></form><div class="admin-list"><article v-for="item in items" :key="item.id" class="admin-row"><div><span class="pill">{{item.kind==='category'?'分类':'标签'}}</span><strong>{{item.name}}</strong></div><div class="row-actions"><button @click="updateTaxonomy(item)">重命名</button><button class="danger-text" @click="deleteItem('taxonomies',item.id,'删除该分类或标签？仍被内容引用时将阻止删除。')">删除</button></div></article></div></template>
    <template v-else-if="section==='settings' && settings"><div class="admin-heading"><h1>让这里更像你</h1></div><form class="content-form" @submit.prevent="saveSettings"><label>网站名称<input v-model="settings.name" required maxlength="60"/></label><h3>首页开场</h3><label>主标题<input v-model="settings.hero_title" maxlength="120" placeholder="记录灵感，分享值得发现的事。"/></label><label>眉题（选填）<input v-model="settings.hero_kicker" maxlength="80"/></label><label>首页短介绍<input v-model="settings.tagline" maxlength="120"/></label><label>开场小字（选填）<input v-model="settings.hero_note" maxlength="120"/></label><label class="check-label"><input type="checkbox" v-model="settings.home_intro_first"/>手机端先展示作者介绍，再展示轮播图</label><h3>首页轮播图</h3><p class="muted">最多 6 张。可直接跳转、先放大再跳转，或仅放大；不添加时首页自动隐藏轮播。</p><div v-for="(slide,i) in settings.carousel" :key="i" class="carousel-editor"><div class="carousel-editor-heading"><strong>第 {{ i+1 }} 张</strong><button type="button" class="danger-text" @click="settings.carousel.splice(i,1)">移除</button></div><div class="image-field"><label>图片地址<input v-model="slide.image" required placeholder="上传后自动填入地址"/></label><label class="button secondary upload-button"><Upload :size="16"/>上传图片<input type="file" accept="image/png,image/jpeg,image/webp" @change="upload($event,'carousel',i)"/></label><img v-if="slide.image" :src="slide.image" alt="轮播图预览"/></div><label>图片标题（选填）<input v-model="slide.title" maxlength="80"/></label><label>点击方式<select v-model="slide.action"><option value="link">直接跳转</option><option value="preview_link">放大后可跳转</option><option value="preview">仅放大观看</option></select></label><label v-if="slide.action!=='preview'">跳转地址<input v-model="slide.url" type="url" required maxlength="2048" placeholder="https://"/></label></div><button v-if="settings.carousel.length<6" type="button" class="button secondary" @click="addSlide"><Plus :size="16"/>添加轮播图</button><h3>个人资料</h3><label>个人简介<textarea v-model="settings.bio" rows="5" maxlength="1000"/></label><div class="image-field"><label>头像地址<input v-model="settings.avatar"/></label><label class="button secondary upload-button">上传头像<input type="file" accept="image/png,image/jpeg,image/webp" @change="upload($event,'avatar')"/></label><img v-if="settings.avatar" :src="settings.avatar" alt="头像预览"/></div><label class="check-label"><input type="checkbox" v-model="settings.placeholder"/>个人资料仍是占位内容，显示提示</label><h3>联系外链</h3><div v-for="(link,i) in settings.links" :key="i" class="link-row"><input v-model="link.label" placeholder="名称" aria-label="链接名称" required maxlength="40"/><input v-model="link.url" placeholder="https://" aria-label="链接地址" type="url" required/><button type="button" @click="settings.links.splice(i,1)">移除</button></div><button v-if="settings.links.length<6" type="button" class="button secondary" @click="settings.links.push({label:'',url:''})">添加外链</button><button class="button" :disabled="busy">保存站点设置</button></form></template>
    <button v-if="more && !editing" class="button secondary load-more" :disabled="busy" @click="page++;load(true)">加载更多</button>
  </div></div>
  <div v-if="preview" class="modal-backdrop" @click.self="preview=null" @keydown.esc="preview=null"><section class="preview-modal" role="dialog" aria-modal="true" aria-label="内容预览" tabindex="-1"><div class="admin-heading"><h2>内容预览 · {{typeLabels[preview.type]}}</h2><button class="button secondary" autofocus @click="preview=null">关闭预览</button></div><p class="notice">{{preview.status==='published'?'内容当前已公开。':'私有预览，仅站长可见。'}}</p><h1>{{preview.title}}</h1><p v-if="preview.summary">{{preview.summary}}</p><img v-if="preview.cover" class="inline-image" :src="preview.cover" alt="封面"/><RichBody :html="preview.body" :toc="preview.type==='article'"/><template v-if="preview.type==='game'"><video v-if="preview.video_url" class="game-video" :src="preview.video_url" controls playsinline preload="metadata">浏览器暂不支持此视频格式。</video><p v-if="preview.device">{{preview.device}}</p><p v-if="preview.instructions" class="plain-text">{{preview.instructions}}</p><div v-if="preview.screenshots.length" class="screenshots"><img v-for="src in preview.screenshots" :key="src" :src="src" alt="截图"/></div></template><a v-if="preview.url" :href="preview.url" target="_blank" rel="noopener noreferrer" class="text-link">查看外部链接 ↗</a></section></div>
</template>
