<script setup>
import { ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ArrowLeft, ArrowUpRight, Heart, Link, MonitorSmartphone } from '@lucide/vue';
import { api, typeLabels, dateLabel } from '../api';
import RichBody from '../components/RichBody.vue';
import Comments from '../components/Comments.vue';
import ContentCard from '../components/ContentCard.vue';
const route = useRoute(), router = useRouter(), item = ref(null), error = ref(''), loading = ref(true), busy = ref(false), notice = ref('');
async function load() { loading.value = true; error.value = ''; try { if (!route.params.id) throw new Error('页面不存在'); item.value = await api('/contents/'+route.params.id); } catch(e) { error.value = e.message; } finally { loading.value = false; } }
watch(() => route.params.id, load, { immediate: true });
function back() { if (window.history.state.back) router.back(); else router.push(item.value?.type === 'game' ? '/games' : '/knowledge'); }
async function like() { busy.value = true; try { item.value = await api(`/contents/${item.value.id}/like`, { method:'PUT', body:{ liked:!item.value.liked } }); } catch(e) { notice.value = e.message; } finally { busy.value = false; } }
async function share() { try { await navigator.clipboard.writeText(location.href); notice.value = '链接已复制'; } catch { notice.value = '请复制浏览器地址栏链接'; } }
</script>
<template>
  <div class="detail-page"><button class="back-button" @click="back"><ArrowLeft :size="17"/>返回列表</button><div v-if="loading" class="state-panel">正在加载内容…</div><div v-else-if="error" class="state-panel" role="alert"><h1>暂时无法打开这篇内容</h1><p>{{ error }}</p><button class="button secondary" @click="load">重新加载</button><RouterLink class="text-link" to="/">回到首页</RouterLink></div>
  <template v-else-if="item"><ContentCard v-if="item.type==='tool'" :item="item"/><article v-else class="article-sheet"><header class="article-header"><div class="card-meta"><span :class="['pill',item.type]">{{ typeLabels[item.type] }}</span><span v-if="item.category">{{ item.category }}</span><span v-if="item.tags.includes('占位示例')" class="sample-label">占位示例</span></div><h1>{{ item.title }}</h1><p v-if="item.summary" class="article-summary">{{ item.summary }}</p><div v-if="item.show_published_at !== false || item.tags.some(t=>t!=='占位示例')" class="article-byline"><time v-if="item.show_published_at !== false && item.published_at">{{ dateLabel(item.published_at) }}</time><span v-for="tag in item.tags.filter(t=>t!=='占位示例')" :key="tag"># {{ tag }}</span></div></header><img v-if="item.cover" class="detail-cover" :src="item.cover" :alt="item.title+'封面'"/><div class="article-body"><div v-if="item.type==='game'" class="game-launch"><span v-if="item.device"><MonitorSmartphone :size="20"/>{{ item.device }}</span><a v-if="item.url" class="button" :href="item.url" target="_blank" rel="noopener noreferrer">前往游戏 <ArrowUpRight :size="17"/></a></div><RichBody v-if="item.body" :html="item.body" :toc="item.type==='article'"/><template v-if="item.type==='game'"><section v-if="item.video_url" class="game-video-section"><h2>游戏宣传视频</h2><video class="game-video" :src="item.video_url" :poster="item.cover || undefined" controls playsinline preload="metadata">浏览器暂不支持此视频格式。</video></section><template v-if="item.screenshots.length"><h2>游戏截图</h2><div class="screenshots"><img v-for="src in item.screenshots" :key="src" :src="src" alt="游戏截图" loading="lazy"/></div></template><template v-if="item.instructions"><h2>操作说明</h2><p class="plain-text">{{ item.instructions }}</p></template></template><a v-if="item.type==='note' && item.url" class="text-link" :href="item.url" target="_blank" rel="noopener noreferrer">相关链接 ↗</a><div class="article-actions"><button :class="['button','secondary',{liked:item.liked}]" :disabled="busy" :aria-pressed="item.liked" @click="like"><Heart :size="17"/>{{ item.liked ? '已点赞' : '觉得有用' }} · {{ item.like_count }}</button><button class="button secondary" @click="share"><Link :size="16"/>分享</button></div><p v-if="notice" class="notice" role="status">{{ notice }}</p><Comments :content-id="item.id"/></div></article></template></div>
</template>
